name: Action CI

on:
  schedule:
    - cron: "0 6 * * *"
  push:
  pull_request:

jobs:
  ci-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    name: Action CI
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }} environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          check-latest: true
      - name: Update dependencies
        run: python3 -m pip install --upgrade pip wheel setuptools
      - name: Python environment report
        run: python -c "import sys; print(sys.version)"
      - name: Action CI - default
        uses: ./
        with:
          subcmd: "--help"
      - name: Action CI - default with single file
        uses: ./
        with:
          subcmd: "check-profile"
          args: "tests/check-test.py"
          path: "tests/NotoSans-Regular.ttf"
      - name: Action CI - default with wildcard path
        uses: ./
        with:
          subcmd: "check-profile"
          args: "tests/check-test.py"
          path: "tests/*.ttf"
      - name: Action CI - fontbakery main branch version
        uses: ./
        with:
          subcmd: "check-profile"
          args: "tests/check-test.py"
          path: "tests/*.ttf"
          version: "main"
      - name: Action CI - fontbakery pinned release version
        uses: ./
